// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqyzIBk8SKs6KAcnG9FuZ3kNdQrmXpkcs',
    appId: '1:1019241871142:web:e07c49fb0b04a2231c73e7',
    messagingSenderId: '1019241871142',
    projectId: 'uzxarid2',
    authDomain: 'uzxarid2.firebaseapp.com',
    storageBucket: 'uzxarid2.firebasestorage.app',
    measurementId: 'G-LN5KS7J955',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Fbsa-m5vM_fRkw-nfkVY1SY1u7uTvpE',
    appId: '1:1019241871142:android:63d09fa98701ae971c73e7',
    messagingSenderId: '1019241871142',
    projectId: 'uzxarid2',
    storageBucket: 'uzxarid2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC94WcewTI1wkQ2gQHmaRN4VR2UkbMs4vM',
    appId: '1:1019241871142:ios:83180e4da04391c91c73e7',
    messagingSenderId: '1019241871142',
    projectId: 'uzxarid2',
    storageBucket: 'uzxarid2.firebasestorage.app',
    iosBundleId: 'uz.uzxarid.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC94WcewTI1wkQ2gQHmaRN4VR2UkbMs4vM',
    appId: '1:1019241871142:ios:7f7fdf9674168a531c73e7',
    messagingSenderId: '1019241871142',
    projectId: 'uzxarid2',
    storageBucket: 'uzxarid2.firebasestorage.app',
    iosBundleId: 'com.example.uzXarid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_pYQBEzdB8r7taEbdPPK8IqUj8UXwN3I',
    appId: '1:1019241871142:web:e6fac00eb979986b1c73e7',
    messagingSenderId: '1019241871142',
    projectId: 'uzxarid2',
    authDomain: 'uzxarid2.firebaseapp.com',
    storageBucket: 'uzxarid2.firebasestorage.app',
    measurementId: 'G-K7PFNER5ZJ',
  );
}